digedag/rn_base

model/class.tx_rnbase_model_media.php
tests/model/class.tx_rnbase_tests_model_Media_testcase.php

die Referenzeigenschaften überschreiben die Eigenschaften der Originaldatei. Aber nur wenn diese nicht leer sind.

Media Bugfix

---

util/class.tx_rnbase_util_Lang.php

To allow loading labels from language file from TYPO3 version >= 4.6
```
$configurations->getLL('LLL:EXT:mklib/locallang.xml:label123')
```

add support for LLL: syntax to getLL from typo3 version 4.6

---

filter/class.tx_rnbase_filter_BaseFilter.php
filter/class.tx_rnbase_filter_FilterItem.php
maps/class.tx_rnbase_maps_TypeRegistry.php
maps/google/class.tx_rnbase_maps_google_Icon.php
model/class.tx_rnbase_model_base.php
model/class.tx_rnbase_model_media.php
tests/class.tx_rnbase_tests_configurations_testcase.php
util/class.tx_rnbase_util_Calendar.php
util/class.tx_rnbase_util_FormatUtil.php
util/class.tx_rnbase_util_ListMarkerInfo.php
util/class.tx_rnbase_util_Queue.php
view/class.tx_rnbase_view_phpTemplateEngine.php

Since PHP 5, constructors in PHP should be named __construct, not as
the class name anymore.

[CLEANUP] Rename all constructors to __construct

---

util/class.tx_rnbase_util_Templates.php

Hi,
the old class `TYPO3\CMS\Core\Html\HtmlParser` is deprecated in TYPO3 7.* and you schould use the `TYPO3\\CMS\\Core\\Service\\MarkerBasedTemplateService`.
So i changed the condition from minimum T3 8.* to T3 7.* ;)

- using MarkerBasedTemplateService with TYPO3 7 or Higher

---

Classes/Utility/Strings.php
class.tx_rnbase_parameters.php
util/class.tx_rnbase_util_FormUtil.php
util/class.tx_rnbase_util_Strings.php

The corresponding Core method has been deprecated as it was not considered to
be really safe. htmlspecialchars should be used instead.

[TASK] Replace usage of the deprecated removeXSS method

---

util/class.tx_rnbase_util_Lang.php
util/class.tx_rnbase_util_TYPO3.php

`GeneralUtility::readLLfile` was deprecated in TYPO3 7.4, not in
version 8.0.
So now `tx_rnbase_util_Lang::readLLfile` will not create deprecation
warnings in TYPO3 7.6 anymore.

[BUGFIX] Fix deprecation warning in TYPO3 7.6 for `readLLfile`

---

composer.json
ext_emconf.php

For `composer.json` one should require `typo3/cms-core` instead of `typo3/cms`due to the subtree split. In summary the main reason is extensions define a dependency on TYPO3 itself (core) instead of each and every system extension. Details: https://usetypo3.com/typo3-subtree-split-and-composer.html
However this needs to drop v6 support as well. This is one step for v9 compatibility, however even with v8 extensions requiring `typo3/cms` are a hassle to maintain.

[TASK] change composer.json for TYPO3 subtree split

---

Classes/Database/Connection.php

This one added the option to force the function lookupLanguage() e.g. when you are in backend context but need the translated record.

force_lookup_language option added

---

Classes/Utility/Misc.php
Classes/Utility/Typo3Classes.php
mod/class.tx_rnbase_mod_BaseModule.php
tests/Classes/Utility/TcaToolTest.php
tests/mod/class.tx_rnbase_tests_mod_Tables_testcase.php
util/class.tx_rnbase_util_Lang.php
util/class.tx_rnbase_util_Templates.php

As we require TYPO3 >= 7.6, there is no need to keep code that is
specific to older TYPO3 versions.

[TASK] Drop code for TYPO3 <= 7.6

---

composer.json

This will make it possible to exclude the tests from packaging, thus
reducing the download size of the extension.

[TASK] Move the test code to the dev autoloading

---

.editorconfig
.gitattributes

This file provides some basic code formatting configuration that
IDEs like PhpStorm can pick up.
The settings in the file reflect what the TYPO3 Core uses in its
`.editorconfig` or in its code.

[TASK] Add an `.editorconfig` file

---

Classes/ExtBaseFluid/ViewHelper/PageBrowserViewHelper.php

Passing the separator after the array (i.e. using the legacy signature) has been deprecated.
https://www.php.net/manual/de/function.implode.php

Fix ordering for implode parameters

---

Classes/Backend/Template/ModuleTemplate.php
Classes/Backend/Template/Override/DocumentTemplate.php
mod/class.tx_rnbase_mod_BaseModule.php

This is not needed anymore with modern HTML versions.

[CLEANUP] Drop `type="text/javascript"` from some `script` tags

---

README.md

Travis CI does not support open source projects for free anymore,
and there have been no new builds for quite some time.

[TASK] Drop the Travis CI badge from the README

---

.github/workflows/php.yaml
composer.json

The namespace of the PHP linting Composer script should match those of
the other CI-related Composer scripts.

[TASK] Make the Composer namespaces consistent

---

Migrations/Code/LegacyClassesForIde.php

This change moves the chunk from `Legacy/extbasefluid.php`.
This change reduces breakage with PHPStan and Rector.

[TASK] Move deprecated class aliases to a migrations file

---

.github/workflows/php.yaml

- clean it up
- use Composer caching (with a PHP-version-specific cache so the cache
can later be shared with other jobs)
- explicitly use Composer 2
- explicitly disable Xdebug for better performance
- use a fixed Ubuntu version to avoid breakage when the "latest" alias
gets changes
- use "composer install" instead of "composer require" as PHP-CS-Fixer
already is a dev dependency
- autoformat the CI configuration with the current `.editorconfig`
settings

[TASK] Streamline the PHP-CS-Fixer check in the CI pipeline

---

composer.json

Some classes provide functionality related to the Scheduler extension,
and some code references to classes from this extension.
So add this extension as a recommendation, and add it as a dev
dependency so static code analysis can analyse the class references.

[TASK] Add a soft requirement on the Scheduler extension

---

Migrations/Code/ClassAliasMap.php
Migrations/Code/LegacyClassesForIde.php
composer.json

This fixes breakage in the mkforms extension that still uses this class.
Fixes #249

[BUGFIX] Add the removed `Tx_Rnbase_Frontend_Plugin` as a class alias

---

Legacy/Controller/AbstractController.php
Migrations/Code/LegacyClassesForIde.php

This class has no alias and has some code of its own. So it
needs to reside in its own autoloaded file instead of being only
stubs for the IDE.

[BUGFIX] Move `AbstractController` into its own file

---

Classes/Backend/Decorator/InterfaceDecorator.php
phpstan-baseline.neon
phpstan.neon
tests/fixtures/classes/class.tx_rnbase_tests_fixtures_classes_Decorator.php

This allows PHPStan to scan the fixture class again. It also fixes
a possible crash in the tests.

[BUGFIX] Align an inconsistent interface in a fixture class

---

Classes/Utility/Typo3Classes.php

- use `::class` where possible with TYPO3 V10
- use `class-string` for annotations
This helps static code analysis (and also the human reader).

[CLEANUP] Improve type information in the `Typo3Classes` class

---

.gitattributes

Now that the test base class is located in `Classes/`, we do not need
to package the `tests/` folder anymore for Packagist.

[TASK] Stop packaging `tests/`

---

composer.json

We now are using a predefined GitHub action for creating TER releases
and don't need this dependency anymore.

[TASK] Drop the TER repository client package

---

phpstan-baseline.neon
tests/Classes/Utility/CryptTest.php
tests/action/class.tx_rnbase_tests_action_CacheHandlerDefault_testcase.php
tests/util/class.tx_rnbase_tests_util_Link_testcase.php
tests/util/class.tx_rnbase_tests_util_Strings_testcase.php

This avoids duplicate key warnings.

[CLEANUP] Stop using `__LINE__` as array key for data providers

---

README.md

This extension does not support TYPO3 7LTS anymore.

[TASK] Drop the badge for TYPO 7.6

---

Classes/Backend/Module/ExtendedModFunc.php
phpstan-baseline.neon

There is no function `boolean` in PHP for casting to a boolean.

[BUGFIX] Fix a boolean cast

---

Classes/Utility/Typo3Classes.php
phpstan-baseline.neon
tests/util/class.tx_rnbase_tests_util_Templates_testcase.php

This class was deprecated in TYPO3 8.0 and should not be used anymore.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Deprecation-73185-DeprecateNullTimeTracker.html

[TASK] Stop using the deprecated `NullTimeTracker`
