class.tx_rnbase_controller.php
exception/class.tx_rnbase_exception_ItemNotFound404.php
tests/class.tx_rnbase_tests_controller_testcase.php
tests/util/class.tx_rnbase_tests_util_TYPO3_testcase.php
util/class.tx_rnbase_util_TYPO3.php

send 404 header and set NOINDEX,FOLLOW robts meta tag if ItemNotFound404 Exception is thrown

send 404 header and set NOINDEX,FOLLOW robts meta tag if ItemNotFound404

---

class.tx_rnbase_configurations.php

Fix #48 it's not a bug - its a feature, and not its an 

---

class.tx_rnbase_configurations.php

- Add PHPDoc
- give methods and attributes a visibility
- give attributes default values
- use real PHPDoc comments
- always use curly braces for ifs

[CLEANUP] Improve the tx_rnbase_configurations PHPDoc (part 1)

---

Classes/Domain/Model/Base.php
model/class.tx_rnbase_model_base.php
util/class.tx_rnbase_util_TCA.php

wie besprochen: auslagern der getUid() Methode, zum Nutzen in mksearch

getUid outsourced in util

---

class.tx_rnbase.php
class.tx_rnbase_configurations.php

This will help static code analysis.

[CLEANUP] Clean up some PHPDoc and add some array type hinting

---

Classes/Domain/Model/Base.php
Classes/Domain/Model/Data.php
model/class.tx_rnbase_model_base.php
model/class.tx_rnbase_model_data.php

Constructors cannot return a value.

[BUGFIX] Remove return values from contructors

---

.travis.yml
composer.json
tests/Classes/Backend/Form/ToolBoxTest.php

PHPUnit-Tests with travis-ci

---

Classes/Fluid/View/Action.php
view/class.tx_rnbase_view_Base.php

[BUGFIX] Make the interfaces of the render method consistent

---

Classes/Backend/Form/ToolBox.php
Classes/Backend/Utility/Tables.php
Classes/Database/Connection.php
class.tx_rnbase_configurations.php
tests/Classes/Utility/MailTest.php
util/class.tx_rnbase_util_FormatUtil.php
util/class.tx_rnbase_util_Lang.php
util/class.tx_rnbase_util_Misc.php
util/class.tx_rnbase_util_SearchBase.php
util/class.tx_rnbase_util_Templates.php

Also drop some obsolete `reset` calls.
This is a partial fix for #117.

[BUGFIX] Drop the use of the deprecated `each` function

---

Classes/Frontend/View/ContextInterface.php

This code fix some bugs in mksearch.

extending interface ArrayAccess in ContextInterface

---

Classes/Utility/Strings.php
util/class.tx_rnbase_util_Strings.php

This helps with static analysis.

[CLEANUP] Add return type annotation for trimExplode

---

.github/workflows/php.yaml

Hey @digedag,
I created a GitHub configuration for GitHub actions, in order to replace style-ci. Maybe this is helping you :)

Add GitHub Actions

---

Classes/Backend/Decorator/InterfaceDecorator.php
Classes/Database/Connection.php
Classes/Domain/Model/Data.php
Classes/Frontend/Filter/Utility/Category.php
mod/class.tx_rnbase_mod_IDecorator.php
tests/Classes/ExtBaseFluid/ViewHelper/BaseViewHelperTest.php
tests/Classes/ExtBaseFluid/ViewHelper/PageBrowserViewHelperTest.php

Some bogus constructs also confused php-cs-fixer.

[CLEANUP] Clean up some PHPDoc annotations

---

Classes/Backend/Module/Linker/ShowDetails.php

This fixes a crash.
Fixes #233

[BUGFIX] Make interface and implementation of `ShowDetails` consistent

---

composer.json

Mostly replace tabs with spaces to match the current `.editorconfig`.

[CLEANUP] Autoformat the `composer.json`

---

.gitattributes
.github/workflows/php.yaml
composer.json
phpstan-baseline.neon
phpstan.neon

This change also adds two new Composer scripts:
- `test:phpstan` checks the types with PHPStan
- `phpstan:baseline` updates the baseline (after problems have been solved)

[FEATURE] Add PHPStan to the CI build

---

Classes/Utility/Language.php

This fixes getting the frontend language for setups that use site
languages (as recommended for TYPO3 >= 9LTS) instead of setting the
language via the legacy `config.language` TypoScript setup.

[BUGFIX] Retrieve the current language from the site language

---

composer.json
ext_emconf.php

[TASK] Require TYPO3 >= 8.7 and drop support for TYPO3 7.6

---

composer.json
phpstan-baseline.neon

Also add a package for PHPStan with Prophecy.

[TASK] Upgrade to PHPStan 1.x

---

composer.json

Also restore the ordering of the Composer requirements.

[TASK] Add TYPO3-specific PHPStan rules

---

phpstan-baseline.neon
tests/util/class.tx_rnbase_tests_util_SimpleMarker_testcase.php

Also improve the type annotations of the affect code parts a bit.

[BUGFIX] Fix access to an undefined variable in a test

---

Classes/ExtBaseFluid/View/Factory.php

Bugfix set missing extbase request

---

Classes/Backend/Utility/BaseLister.php

Fix undefined array key warnings
